providers = ['elixir']

[variables]
NIXPACKS_ELIXIR_VERSION = 'latest'
MIX_ENV = 'prod'
LANG='en_US.UTF-8'

[phases.setup]
nixpkgsArchive = 'a1291d0d020a200c7ce3c48e96090bfa4890a475'
nixPkgs = [
    '...',
    'gcc',
    'gnumake',
    'inotify-tools',
    'nodejs-18_x'
]
cmds = [
    'mix local.hex --force',
    'mix local.rebar --force',
    'mix deps.get --only prod',
    'npm install',
]

[phases.build]
cmds = [
    'mix compile',
    'mix assets.deploy'
]

[start]
cmd = 'mix phx.server'
